

const books = [
    {
    titel: "Das verlorene Paradies",
    autor : "Abdulrazak, Gurnah",
    image: "https://www.kulturkaufhaus.de/annotstream/9783328602583/COPL/Gurnah-Abdulrazak/Das-verlorene-Paradies.jpg?sq=7",
    preis :"25,00",
    sprache : "Deutsch",
    seiten : "336",
    beschreibung : `Ostafrika, Ende des 19. Jahrhunderts: Der zwölfjährige Yusuf führt mit seiner
    Familie ein einfaches Leben auf dem Land. Als der Vater sich mit seinem
    kleinen Hotel verschuldet, wird Yusuf in die Hände von Onkel Aziz gegeben und
    landet im lebhaften Treiben der Stadt, zwischen afrikanischen Muslimen,
    christlichen Missionaren und indischen Geldverleihern. Die Gemeinschaft
    dieser Menschen ist alles andere als selbstverständlich und von subtilen
    Hierarchien bestimmt. Yusuf hilft in Aziz Laden und bei der Pflege seines
    paradiesisch anmutenden Gartens. Doch als der Kaufmann ihn auf eine
    Karawanenreise ins Landesinnere mitnimmt, endet Yusufs Jugend abrupt. Die
    gefährliche Unternehmung bringt Krankheit und Tod und zeigt allen Teilnehmern
    schmerzhaft, dass die traditionelle Art des Handels keine Zukunft mehr hat.
    Was Yusuf erlebt, lässt ihn erwachsen werden. So verliebt sich der junge Mann
    nach seiner Heimkehr kopfüber, aber er und alle um ihn herum werden brutal
    mit der neuen Realität der deutschen Kolonialherrschaft konfrontiert.
    Einfühlsam, lebendig und in leichtem, humorvollem Ton, erzählt Abdulrazak
    Gurnah in »Das verlorene Paradies« vom Erwachsenwerden in Zeiten des
    kolonialen Umbruchs. Im Original 1994 erschienen, stand der Roman u.a. auf
    der Shortlist des Booker Prize und stellte für Gurnah den Durchbruch als
    Schriftsteller dar. Jetzt ist er endlich wieder in der Übersetzung von Inge
    Leipold auf Deutsch zu lesen.`,
    kategorie:"Neu und Bestseller",
    "ISBN/GTIN": "978-3-328-60258-3",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Penguin Verlag München",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"08.12.2021",
    Gewicht:"545 g",
    ArtikelNr:"16430532",
    Genre:"Belletristik"
    },
    {titel: "Vernichten",
    autor : "Michel, Houellebecq",
    image: "https://www.kulturkaufhaus.de/annotstream/9783832181932/COPL/Houellebecq-Michel/Vernichten.jpg?sq=2",
    preis :"28,00",
    sprache : "Deutsch",
    seiten : "624",
    beschreibung : `Kurz vor den französischen Präsidentschaftswahlen 2027 taucht im Netz ein Video auf, das die Hinrichtung des möglichen Kandidaten Bruno Juge zu zeigen scheint. Paul Raison ist Absolvent einer Elitehochschule und arbeitet als Spitzenbeamter im Wirtschaftsministerium. Als Mitarbeiter und Vertrautem Juges fällt ihm die Aufgabe zu, die Urheber des Videos ausfindig zu machen. Im Laufe seiner Nachforschungen kommt es zu einer Serie mysteriöser terroristischer Anschläge, zwischen denen kein Zusammenhang zu erkennen ist. Aber nicht nur die Arbeit, auch das Privatleben von Paul Raison ist alles andere als einfach. Er und seine Frau Prudence leben zwar noch zusammen, aber sie teilen nichts mehr miteinander. Selbst die Fächer im Kühlschrank sind getrennt. Während Juge um seine Kandidatur kämpft, kann Paul entscheidende Hinweise für die Aufklärung der Anschläge liefern. Doch letztlich verliert Juge gegen einen volksnahen ehemaligen Fernsehmoderator, und die Erkenntnisse aus Pauls Recherche sind nicht minder niederschmetternd für die Politik des Landes. Als Paul von seiner Arbeit freigestellt wird, kommt es zu einer Annäherung zwischen ihm und seiner Frau und die beiden finden wieder zueinander. Ein unerwartetes, wenn auch fragiles Glück ... Die Möglichkeiten und Unmöglichkeiten der Liebe, das komplexe Zusammenspiel von Gesellschaft und Politik und die weitreichende, oftmals kaum wahrnehmbare Verknüpfung von Politischem und Privatem - das sind die Themen des neuen Romans von Michel Houellebecq, dem großen Visionär der französischen Literatur.`,
    kategorie:"Neu und Bestseller",
    "ISBN/GTIN": "978-3-8321-8193-2",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"DuMont Buchverlag",
    Erscheinungsjahr:"2022",
    Erstverkaufstag:"11.01.2022",
    ArtikelNr:"16431062",
    Genre:"Belletristik"
    },
    {titel: "Zum Paradies",
    autor : "Hanya, Yanagihara",
    image: "https://www.kulturkaufhaus.de/annotstream/9783546100519/COPL/Yanagihara-Hanya/Zum-Paradies.jpg?sq=5",
    preis :"24,99",
    sprache : "Deutsch",
    seiten : "896",
    beschreibung : `»Tiefgründig, sensibel, spannend und ausreichend lang für meinen Geschmack.« Juli Zeh, Börsenblatt
    Drei Jahrhunderte, drei Versionen des amerikanischen Experiments: In ihrem kühnen neuen Roman - dem ersten seit Ein wenig Leben - erzählt Hanya Yanagihara von Liebenden, von Familie, vom Verlust und den trügerischen Versprechen gesellschaftlicher Utopien.
    1893, in einem Amerika, das anders ist, als wir es aus den Geschichtsbüchern kennen: New York gehört zu den Free States, in denen die Menschen so leben und so lieben, wie sie es möchten - so jedenfalls scheint es. Ein junger Mann, Spross einer der angesehensten und wohlhabendsten Familien, entzieht sich der Verlobung mit einem standesgemäßen Verehrer und folgt einem charmanten, mittellosen Musiklehrer.
    1993, in einem Manhattan im Bann der AIDS-Epidemie: Ein junger Hawaiianer teilt sein Leben mit einem deutlich älteren, reichen Mann, doch er verschweigt ihm die Erschütterungen seiner Kindheit und das Schicksal seines Vaters.
    2093, in einer von Seuchen zerrissenen, autoritär kontrollierten Welt: Die durch eine Medikation versehrte Enkelin eines mächtigen Wissenschaftlers versucht ohne ihn ihr Leben zu bewältigen - und herauszufinden, wohin ihr Ehemann regelmäßig an einem Abend in jeder Woche verschwindet.
    Drei Teile, die sich zu einer aufwühlenden, einzigartigen Symphonie verbinden, deren Themen und Motive wiederkehren, nachhallen, einander vertiefen und verdeutlichen: Ein Town House am Washington Square. Krankheiten, Therapien und deren Kosten. Reichtum und Elend. Schwache und starke Menschen. Die gefährliche Selbstgerechtigkeit von Mächtigen und von Revolutionären. Die Sehnsucht nach dem irdischen Paradies - und die Erkenntnis, dass es nicht existiert. Und all das, was uns zu Menschen macht: Angst. Liebe. Scham. Bedürfnis. Einsamkeit.
    Zum Paradies ist ein Wunderwerk literarischer Erfindungskraft und ein Kunstwerk menschlicher Gefühle. Seine außergewöhnliche Wirkung gründet in seinem Wissen um den Wunsch, jene zu beschützen, die wir lieben: Partner, Liebhaber, Kinder, Freunde - unsere Mitmenschen. Und den Schmerz, der nach uns greift, wenn wir das nicht können.`,
    kategorie:"Neu und Bestseller",
    "ISBN/GTIN": "978-3-546-10051-9",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Claassen Verlag",
    Erscheinungsjahr:"2022",
    Erstverkaufstag:"11.01.2022",
    Gewicht:"875 g",
    ArtikelNr:"19648141",
    Genre:"Belletristik"
    },
    {titel: "Einer von euch",
    autor : "Martin, Suter",
    image: "https://www.kulturkaufhaus.de/annotstream/9783257071689/COPL/Suter-Martin/Einer-von-euch.jpg?sq=4",
    preis :"26,00",
    sprache : "Deutsch",
    seiten : "384",
    beschreibung : `Bastian Schweinsteiger, der Held des WM-Finales 2014 in Rio, ist auch der Held des neuen Romans von Martin Suter. Der Autor erzählt uns Wahres und fast Wahres aus dem Leben des Mannes, dem es nicht in die Wiege gelegt war, alles zu erreichen, was man als Fußballer erreichen kann. Und er verrät uns auch, wie Basti dennoch so erfolgreich wurde. Nur so viel sei verraten: nicht aus Ehrgeiz. Aus Freude am Erfolg.`,
    kategorie:"Neu und Bestseller",
    "ISBN/GTIN": "978-3-257-07168-9",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Diogenes",
    Erscheinungsjahr:"2022",
    Erstverkaufstag:"26.01.2022",
    ArtikelNr:"19543813",
    Genre:"Belletristik"
    },
    {titel: "Strömung",
    autor : "Jakob, Augstein",
    image: "https://www.kulturkaufhaus.de/annotstream/9783351039493/COPL/Augstein-Jakob/Str%C3%B6mung.jpg?sq=2",
    preis :"22,00",
    sprache : "Deutsch",
    seiten : "301",
    beschreibung : `Dass alte Gewissheiten schwinden, dass die Welt sich schneller ändert, als er es für möglich gehalten hätte, wird Misslinger ausgerechnet in den USA klar, dem Ort, der für ihn immer noch für Freiheit und eine bessere Zukunft steht. Hier verschwimmen die Grenzen von Traum und Wirklichkeit, und Misslinger realisiert, dass ihm sein Leben längst entglitten ist.
    In seinem grandiosen literarischen Debüt erzählt Jakob Augstein eindringlich von einem Mann unserer Zeit, deren Konturen zwischen politischen Umbrüchen, neuen Ideen und alten Bedrohungen immer schwerer auszumachen sind.`,
    kategorie:"Neu und Bestseller",
    "ISBN/GTIN": "978-3-351-03949-3",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Aufbau-Verlag",
    Erscheinungsjahr:"2022",
    Erstverkaufstag:"17.01.2022",
    Gewicht:"20 g",
    ArtikelNr:"16430740",
    Genre:"Belletristik"
    },
    {titel: "Liebe in Zeiten des Hasses",
    autor : "Florian, Illies",
    image: "https://www.kulturkaufhaus.de/annotstream/9783103970739/COPL/Illies-Florian/Liebe-in-Zeiten-des-Hasses.jpg?sq=13",
    preis :"24,00",
    sprache : "Deutsch",
    seiten : "432",
    beschreibung : `»Lesen Sie bitte dieses Buch, es ist hinreißend. Ich habe so viel Neues erfahren, über die Liebe, die Kunst und das Grauen.« Ferdinand von Schirach
    In einem virtuosen Epochengemälde erweckt Florian Illies die dreißiger Jahre, dieses Jahrzehnt berstender politischer und kultureller Spannungen, zum Leben.
    Als Jean-Paul Sartre mit Simone de Beauvoir im Kranzler-Eck in Berlin Käsekuchen isst, Henry Miller und Anaïs Nin wilde Nächte in Paris und »Stille Tage in Clichy« erleben, F. Scott Fitzgerald und Ernest Hemingway sich in New York in leidenschaftliche Affären stürzen, fliehen Bertolt Brecht und Helene Weigel wie Katia und Thomas Mann ins Exil. Genau das ist die Zeit, in der die Nationalsozialisten die Macht in Deutschland ergreifen, Bücher verbrennen und die Gewalt gegen Juden beginnt.
    1933 enden die »Goldenen Zwanziger« mit einer Vollbremsung. Florian Illies führt uns zurück in die Epoche einer singulären politischen Katastrophe, um von den größten Liebespaaren der Kulturgeschichte zu erzählen: In Berlin, Paris, im Tessin und an der Riviera stemmen sich die großen Helden der Zeit gegen den drohenden Untergang. Eine mitreißend erzählte Reise in die Vergangenheit, die sich wie ein Kommentar zu unserer verunsicherten Gegenwart liest: Liebe in Zeiten des Hasses.`,
    kategorie:"Empfehlungen",
    "ISBN/GTIN": "978-3-10-397073-9",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"S.Fischer Verlag GmbH",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"27.10.2021",
    Gewicht:"640g",
    ArtikelNr:"19765871",
    Genre:"Sachbuch"
    },
    {titel: "Das NEINhorn und die SchLANGEWEILE",
    autor : "Marc-Uwe, Kling",
    image: "https://www.kulturkaufhaus.de/annotstream/9783551521286/COPL/Kling-Marc-Uwe/Das-NEINhorn-und-die-SchLANGEWEILE.jpg?sq=6",
    preis :"13,00",
    sprache : "Deutsch",
    seiten : "54",
    beschreibung : `Das NEINhorn und die KönigsDOCHter, die hatten einen Streit ...
    ... aber beide wissen nicht mehr, worum es geht.
    Als sich der NAhUND zum Erzieher aufspielt, wird es dem NEINhorn zu blöd und es zischt ab. Nach einer langen Wanderung landet es im dichten dunklen Dschungel, wo die SchLANGEWEILE von einem Assst runterhängt und allesss sssuper schlangweilig findet! Egal, was das NEINhorn vorschlägt, sie hat keine Schlussst darauf.
    Ob sich das NEINhorn von der SchLANGEWEILE einwickeln lässt?
    Mit phänomenaler Panorama-Ausklappseite Mit Schleiterspiel für noch mehr Spaß Mit Eintragseite zum Mitmachen Und mit vielen weiteren witzigen Tieren
    Eine neue witzige Geschichte von Marc-Uwe Kling über das schnickeldischnuckelig süße NEINhorn und seinen Umgang mit der SchLANGEWEILE - zum Vorlesen, Selbstlesen, Lachen und Entdecken. Großartig illustriert von Astrid Henn.`,
    kategorie:"Empfehlungen",
    "ISBN/GTIN": "978-3-551-52128-6",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Carlsen",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"29.11.2021",
    Gewicht:"441 g",
    ArtikelNr:"19761016",
    Genre:"Kinder- und Jugendbücher | Bilderbücher"
    },
    {titel: "Die Enkelin",
    autor : "Bernhard, Schlink",
    image: "https://www.kulturkaufhaus.de/annotstream/9783257071818/COPL/Schlink-Bernhard/Die-Enkelin.jpg?sq=4",
    preis :"25,00",
    sprache : "Deutsch",
    seiten : "368",
    beschreibung : `Birgit ist zu Kaspar in den Westen geflohen, für die Liebe und die Freiheit. Erst nach ihrem Tod entdeckt er, welchen Preis sie dafür bezahlt hat. Er spürt ihrem Geheimnis nach, begegnet im Osten den Menschen, die für sie zählten, erlebt ihre Bedrückung und ihren Eigensinn. Seine Suche führt ihn zu einer völkischen Gemeinschaft auf dem Land - und zu einem jungen Mädchen, das in ihm den Großvater und in dem er die Enkelin sieht. Ihre Welten könnten nicht fremder sein. Er ringt um sie.`,
    kategorie:"Empfehlungen",
    "ISBN/GTIN": "978-3-257-07181-8",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Diogenes",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"27.10.2021",
    ArtikelNr:"20323465",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Belletristik | Erzählende Literatur",
    autor : "Jonathan, Franzen",
    image: "https://www.kulturkaufhaus.de/annotstream/9783498020088/COPL/Franzen-Jonathan/Crossroads.jpg?sq=6",
    preis :"28,00",
    sprache : "Deutsch",
    seiten : "832",
    beschreibung : `Ein Roman über eine Familie am Scheideweg: über Sehnsucht und Geschwisterliebe, über Lügen, Geheimnisse und Rivalität. Der Auftakt zu Jonathan Franzens Opus magnum «Ein Schlüssel zu allen Mythologien» - einer Trilogie über drei Generationen einer Familie aus dem Mittleren Westen und einem der größten literarischen Projekte dieser Zeit.
    Es ist der 23. Dezember 1971, und für Chicago sind Turbulenzen vorhergesagt. Russ Hildebrandt, evangelischer Pastor in einer liberalen Vorstadtgemeinde, steht im Begriff, sich aus seiner Ehe zu lösen - sofern seine Frau Marion, die ihr eigenes geheimes Leben lebt, ihm nicht zuvorkommt. Ihr ältester Sohn Clem kehrt von der Uni mit einer Nachricht nach Hause zurück, die seinen Vater moralisch schwer erschüttern wird. Clems Schwester Becky, lange Zeit umschwärmter Mittelpunkt ihres Highschool-Jahrgangs, ist in die Musikkultur der Ära ausgeschert, während ihr hochbegabter jüngerer Bruder Perry, der Drogen an Siebtklässler verkauft, den festen Vorsatz hat, ein besserer Mensch zu werden. Jeder der an einem Scheideweg stehenden Hildebrandts sucht eine Freiheit, die jeder der anderen zu durchkreuzen droht.
    Jonathan Franzen ist berühmt für seine Gegenwartspanoramen mit ihren unvergesslich lebendigen Figuren. Jetzt, in «Crossroads», einer aus mehreren Perspektiven erzählten Geschichte, die sich im Großen und Ganzen an einem einzigen Wintertag entrollt, nimmt er den Leser mit in die Vergangenheit und beschwört eine Welt herauf, die in der heutigen noch nachhallt. Ein Familienroman von beispielloser Kraft und Tiefe, mal komisch, mal zutiefst bewegend und immer spannungsreich: ein fulminantes Werk, in dem Jonathan Franzens Gabe, im Kleinen das Große zu zeigen, in Erscheinung tritt wie nie zuvor.
    «Jonathan Franzen ist einer der größten lebenden Schriftsteller, und seine Romane gehören zum Kanon der großen amerikanischen Familien- und Sozialepen.»
    DER SPIEGEL`,
    kategorie:"Empfehlungen",
    "ISBN/GTIN": "978-3-498-02008-8",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Rowohlt",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"05.10.2021",
    Gewicht:"971 g",
    ArtikelNr:"16402655",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Ottolenghi Test Kitchen - Shelf Love",
    autor : "Yotam, Ottolenghi",
    image: "https://www.kulturkaufhaus.de/annotstream/9783831042944/COPL/Ottolenghi-Yotam/Ottolenghi-Test-Kitchen---Shelf-Love.jpg?sq=10",
    preis :"24,95",
    sprache : "Deutsch",
    seiten : "256",
    beschreibung : `Entspannt kochen mit dem Ottolenghi-Team
    Für dieses außergewöhnliche Kochbuch hat Weltbestsellerautor Yotam Ottolenghi sein Test Kitchen-Team bestehend aus Noor Murad, Verena Lochmuller, Tara Wigley und Gitai Fischer zusammengetrommelt. Und sie zeigen, wie einfach es ist mit bereits vorhandenen Zutaten aus der eigenen Küche einfache und köstlich schmeckende Kreationen zu kochen und ihnen dabei den besonderen Ottolenghi-Twist zu geben!
    Simple Ottolenghi-Rezepte für den Alltag
    Bringen Sie mehr Schwung in Ihre Küche - und zwar einfach mit dem, was Sie zu Hause da haben! Ob cremiger Hummus, unkompliziertes One Pot Chicken oder Blumenkohl-Käse-Kuchen - dieses Ottolenghi-Kochbuch überzeugt mit 90 einfachen Alltagsrezepten, die dennoch raffiniert und köstlich schmecken. Der typische Wow-Effekt von Ottolenghi verleiht den Gerichten das gewisse Etwas: Freuen Sie sich auf vielfältige Aromen, kreative Vielseitigkeit und innovative Einflüsse des Ottolenghi Test Kitchen-Teams!
    - Einfach Alltagsrezepte mit Zutaten aus dem Küchenregal: Was kann man alles aus einer Dose Kichererbsen oder einem Beutel tiefgefrorener Erbsen zaubern? Die Antwort liefern die flexiblen und originellen Ottolenghi-Rezepte, die das Beste aus den Zutaten holen, die Ihnen zu Hause zur Verfügung stehen.
    - Originelle Anregungen aus der Profiküche der Ottolenghi Test Kitchen: Schaffen Sie sich Ihre eigene Testküche im Ottolenghi-Style und experimentieren Sie mit fantasievollen Gerichten, die flexibel abgewandelt werden können - wie z.B. Tabouleh-Bratlinge, Persische Kräuter-Feta-Taschen oder Blaubeeren-Zitronen-Sahne-Schnitten.
    - Das erste Buch der neuen Kochbuchserie von Ottolenghis grandiosem Test Kitchen-Team
    Innovative Alltagsrezepte im Ottolenghi-Style! Zusammen mit Ottolenghis Test Kitchen-Team zaubern Sie köstliche Gerichte, aus Zutaten, die Sie bereits zu Hause haben!`,
    kategorie:"Empfehlungen",
    "ISBN/GTIN": "",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Dorling Kindersley Verlag",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"04.10.2021",
    Gewicht:"770 g",
    ArtikelNr:"19537777",
    Genre:"Themenkochbücher"
    },
    {titel: "Memoiren eines Irren",
    autor : "Gustave, Flaubert",
    image: "https://www.kulturkaufhaus.de/annotstream/9783446268456/COPL/Flaubert-Gustave/Memoiren-eines-Irren.jpg?sq=1",
    preis :"28,00",
    sprache : "Deutsch",
    seiten : "240",
    beschreibung : `Witzig, romantisch, bösartig - Gustave Flauberts erster Roman in neuer ÜbersetzungEin junger Bursche beobachtet unter den Sommergästen in Trouville eine Frau, die ihn fasziniert. Als er ihren Bademantel vor der Flut rettet und zurückbringt, verliebt er sich auf der Stelle. Maria jedoch ist zehn Jahre älter als er, hat einen Mann und eine kleine Tochter. Mit ungeheurer Leidenschaft erzählt der junge Flaubert in seinem ersten Roman die eigene Geschichte, die ihn für ein Leben geprägt hat. In der Neuübersetzung von Elisabeth Edl, mit Jugendbriefen und einem Kommentar, der den biografischen Hintergrund farbig sichtbar macht, sind die "Memoiren eines Irren" das Selbstporträt eines Künstlers als junger Mann, der zu seinem 200. Geburtstag als einer der Größten gefeiert wird.`,
    kategorie:"Klassiker",
    "ISBN/GTIN": "978-3-446-26845-6",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Gebunden",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"25.10.2021",
    Gewicht:"293 g",
    ArtikelNr:"16414403",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Vom Verachtetwerden oder Drei Guineen",
    autor : "Virginia, Woolf",
    image: "https://www.kulturkaufhaus.de/annotstream/9783311220053/COPL/Woolf-Virginia/Vom-Verachtetwerden-oder-Drei-Guineen.jpg?sq=1",
    preis :"24,00",
    sprache : "Deutsch",
    seiten : "256",
    beschreibung : `Immer wieder hat sich Virginia Woolf mit der Frauenfrage befasst. Am berühmtesten ist wohl ihr hellsichtiger Essay Ein Zimmer für sich allein (1929). In Vom Verachtetwerden, zehn Jahre spater erschienen, ist Woolfs Ton weniger ironisch, ihre Haltung unnachgiebiger. Kurz vor Ausbruch des Zweiten Weltkriegs fragt sie sich, wie Frauen einen Krieg verhindern sollen, wenn sie ausgeschlossen sind von Aufgaben in Offentlichkeit und Politik, und übt damit grundsatzliche Kritik am Patriarchat. Auf eindrückliche Weise verbindet Woolf hier schon früh das Private mit dem Politischen, den Aufstieg der Faschisten mit grundsatzlichen gesellschaftlichen Macht- und Denkstrukturen: Die Wurzel des Faschismus liege in der Vorherrschaft des Mannes in samtlichen Lebensbereichen. Aber Woolf kritisiert nicht nur, sondern entwirft auch ein utopisches Gesellschaftmodell, eine Welt, in der Frauen Familie und Erwerbstatigkeit verbinden, sich in Ausbildung und Beruf frei entfalten, wirtschaftliche Unabhangigkeit und intellektuelle Freiheit erreichen: So konnten Frauen für dieselbe Sache arbeiten und kampfen wie Manner, auf Augenhohe mit ihnen. Woolfs noch heute hochaktueller Essay macht deutlich, dass Terror, Unrecht, Autoritarismus nur dann wirklich aus der Welt zu schaffen sind, wenn sie auch im »Kleinen« erkannt und bekampft werden.`,
    kategorie:"KLassiker",
    "ISBN/GTIN": "978-3-311-22005-3",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Kampa Verlag",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"23.09.2021",
    ArtikelNr:"19605553",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Aufzeichnungen aus einem toten Haus",
    autor : "Fjodor M., Dostojewski",
    image: "https://www.kulturkaufhaus.de/annotstream/9783446265738/COPL/Dostojewski-Fjodor-M./Aufzeichnungen-aus-einem-toten-Haus.jpg?sq=2",
    preis :"36,00",
    sprache : "Deutsch",
    seiten : "544",
    beschreibung : `Fjodor M. Dostojewskis großer autobiographischer Roman in neuer ÜbersetzungAm Anfang steht ein Mord: Alexánder Petrówitsch Gorjántschikow wird zu zehn Jahren Zwangsarbeit verurteilt. Der verwöhnte Adelige kommt nach Sibirien ins Lager. Der Schock von Verbrechen und Strafe verändert ihn zutiefst, und so beginnt er den Bericht über das, was ihm und seinen Leidensgefährten Tag für Tag widerfährt. Dostojewski schreibt aus eigenem Erleben: 1849 wurde er wegen revolutionärer Umtriebe zum Tode verurteilt, nach einer Scheinhinrichtung deportiert und verbrachte vier Jahre in Ketten. "Aufzeichnungen aus einem toten Haus" gehört zu seinen größten Büchern. Nach Tolstois "Krieg und Frieden" (Preis der Leipziger Buchmesse) hat Barbara Conrad nun auch dieses Meisterwerk neu übersetzt.`,
    kategorie:"Klassiker",
    "ISBN/GTIN": "978-3-446-26573-8",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Hanser",
    Erscheinungsjahr:"2020",
    Erstverkaufstag:"09.03.2020",
    Gewicht:"340 g",
    ArtikelNr:"16275045",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Little Women",
    autor : "Louisa May, Alcott",
    image: "https://www.kulturkaufhaus.de/annotstream/9783150113578/COPL/Alcott-Louisa-May/Little-Women.jpg?sq=4",
    preis :"36,00",
    sprache : "Deutsch",
    seiten : "592",
    beschreibung : `Sisters are forever! Über die Freundschaft von vier Schwestern »Little Women« - das sind die vier Schwestern March, und es ist die Geschichte einer Schriftstellerin, die nach Unabhängigkeit strebte und dabei einen Welterfolg schuf. Louisa May Alcott legte viel von sich selbst in Jo, die zweitälteste der vier Schwestern, und lässt auch sie von einer Karriere als Schriftstellerin träumen. Zwar ist das - wie so vieles andere - für eine Frau in der zweiten Hälfte des 19. Jahrhunderts nicht leicht, doch Jo, Meg, Beth und Amy gehen ihren Weg - gemeinsam und doch jede für sich. Mit Pinsel und Stift ist die Künstlerin Kera Till ins Neuengland der 1860er Jahre eingetaucht und hat die unterschiedlichen Charaktere der vier Schwestern mit schwärmerischen Details, floralen Elementen und verträumten Mustern eingefangen. In diesem Band finden sich Teil I und Teil II in vollständiger Neuübersetzung.»Ich will etwas Großartiges machen, etwas Heldenhaftes und Wundervolles, das nach meinem Tod unvergessen bleibt. Ich weiß noch nicht, was, aber ich halte die Augen offen und habe vor, euch alle eines Tages in Staunen zu versetzen. Ich glaube, ich werde Bücher schreiben und reich und berühmt werden.« (Jo March)`,
    kategorie:"Klassiker",
    "ISBN/GTIN": "978-3-15-011357-8",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Reclam",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"08.10.2021",
    ArtikelNr:"19896888",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Der Geldverleiher",
    autor : "Catherine, Gore",
    image: "https://www.kulturkaufhaus.de/annotstream/9783847704416/COPL/Fontane-Theodor/Der-Geldverleiher.jpg?sq=2",
    preis :"44,00",
    sprache : "Deutsch",
    seiten : "42",
    beschreibung : `Ein verblüffender Fund: Der junge Theodor Fontane entdeckt die viktorianische Erfolgsautorin Catherine Gore - Fontanes Übersetzung zeigt den werdenden Romancier.
    Catherine Gore (1799-1861), eine der meistgelesenen Autorinnen ihrer Zeit, porträtierte in ihrem 1842 in Fortsetzungen
    erschienenen Gesellschaftsroman Der Geldverleiher die englische Gesellschafts- und Finanzwelt. Mit drastischem Realismus und ihrer Beschreibungs- und Beobachtungskunst demaskiert sie eine Epoche voller Standesdünkel und antijüdischer Vorurteile. Theodor Fontane (1819-1898) hat den Roman der Zeitgenossin von der britischen Insel mit einer erstaunlichen Sprach- und Stilsicherheit übertragen - lange bevor er seine berühmten Romane schrieb, die ihn zum großen Klassiker des bürgerlichen Realismus machten.
    Auf Grundlage eines wiederentdeckten Typoskripts hat der Literaturwissenschaftler, Historiker und Fontane-Biograph
    Iwan-Michelangelo D'Aprile dieses übersetzerische Meisterstück aus Fontanes jungen Jahren ediert; sein Vorwort erhellt ein fehlendes Stück in Fontanes Gesamtwerk und bereichert uns um die Kenntnis seiner englischen Vorbilder.
    "Ein richtiger Schmöker. Ein äußerst interessantes Buch des Übergangs von der romantischen Schauergeschichte zum
    realistischen Roman ... Gore wollte unterhalten, und das ist ihr sehr gelungen." - Jürgen Kaube, Frankfurter Allgemeine Zeitung`,
    kategorie:"Klassiker",
    "ISBN/GTIN": "978-3-8477-0441-6",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"AB - Die Andere Bibliothek",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"19.10.2021",
    Gewicht:"733 g",
    ArtikelNr:"19774330",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Die Dorfschullehrerin",
    autor : "Eva, Völler",
    image: "https://www.kulturkaufhaus.de/annotstream/9783785727652/COPL/V%C3%B6ller-Eva/Die-Dorfschullehrerin.jpg?sq=14",
    preis :"14,99",
    sprache : "Deutsch",
    seiten : "448",
    beschreibung : `Eine junge Frau und die Herausforderung ihres Lebens
    1961: Als die Berliner Lehrerin Helene ihre neue Stelle in Hessen an der deutsch-deutschen Grenze antritt, begegnet man ihr im ländlichen, erzkatholischen Ort zunächst mit Ablehnung. Der althergebrachte drakonische Erziehungsstil, die Gleichgültigkeit der Kollegen - für die engagierte Helene ist es ein Kampf gegen Windmühlen. In Tobias, dem Landarzt, findet sie schließlich einen Verbündeten. Schon bald bedeutet er ihr mehr, als ihr lieb ist. Denn Helene hat ein Geheimnis - sie ließ sich nicht ohne Grund genau an diesen Ort versetzen ...`,
    kategorie:"Romane",
    "ISBN/GTIN": "978-3-7857-2765-2",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Bastei Lübbe",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"26.11.2021",
    ArtikelNr:"19692490",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Das Seidenraupenzimmer",
    autor : "Sayaka, Murata",
    image: "https://www.kulturkaufhaus.de/annotstream/9783351037932/COPL/Murata-Sayaka/Das-Seidenraupenzimmer.jpg?sq=2",
    preis :"20,00",
    sprache : "Deutsch",
    seiten : "256",
    beschreibung : `Der neue Roman nach dem Bestseller »Die Ladenhüterin« Der neue Roman von Japans Erfolgsautorin Sayaka Murata erzählt die Geschichte von Natsuki und ihrem Cousin Yu, die sich jung verlieben und gemeinsam gegen eine Welt verbünden, die ihnen beileibe nicht nur Gutes will. Im alten Farmhaus der Familie, in dem früher die Seidenraupen ihren Dienst verrichteten, sind sie glücklich, denn sie sind beieinander. 20 Jahre später geht Natsuki an diesen Ort zurück ... Die Magie dieses abgründigen Romans spinnt uns ein in einen irisierenden Kokon der Fremdheit und entlässt uns schließlich in eine Realität, in der alles möglich ist. Sayaka Muratas Roman »Die Ladenhüterin« war eine literarische Sensation aus Japan, die auch die deutschen Leserinnen und Leser im Sturm erobert hat: Eine Außenseiterin findet als Angestellte eines 24-Stunden-Supermarkts ihre wahre Bestimmung. »Das Seidenraupenzimmer« erzählt die Geschichte von Außenseitern, die darum kämpfen, ihren Platz in der Welt zu finden, noch konsequenter: Wie Murata das Psychogramm eines Missbrauchsopfers überführt in eine gänzlich eigenständige Erzählung, die die Grenzen der Realität einreißt und neu bestimmt, ist beeindruckend - und die so überraschenden Wege der Freundschaft und Liebe, in der die Versehrten Zuflucht finden, sind umso tröstlicher und berührender. »Sehr lustig, aufregend beunruhigend und vollkommen überraschend.« Sally Rooney über »Die Ladenhüterin«`,
    kategorie:"Romane",
    "ISBN/GTIN": "978-3-351-03793-2",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Aufbau-Verlag",
    Erscheinungsjahr:"2020",
    Erstverkaufstag:"15.06.2020",
    Gewicht:"394 g",
    ArtikelNr:"16729235",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Die Surrealistin",
    autor : "Michaela, Carter",
    image: "https://www.kulturkaufhaus.de/annotstream/9783463000015/COPL/Carter-Michaela/Die-Surrealistin.jpg?sq=2",
    preis :"22,00",
    sprache : "Deutsch",
    seiten : "528",
    beschreibung : `Ein packender Roman über eine der wichtigsten Vertreterinnen des Surrealismus
    1937. Als die junge Engländerin Leonora Carrington den berühmten Surrealisten Max Ernst kennenlernt, ist er ein verheirateter Mann. Er führt sie in die Pariser Künstlerszene um Salvador Dalì und Pablo Picasso ein, und bald wird aus der leidenschaftlichen Affäre eine Liebesbeziehung. Das Paar zieht nach Südfrankreich, wo Carrington sich der Malerei verschreibt.
    Doch dann bricht der 2. Weltkrieg aus, Max Ernst wird von den Franzosen inhaftiert. Jahre später findet er ihr gemeinsames Haus leer vor. Er macht sich auf die Suche nach ihr. Doch Leonora hat mittlerweile begonnen, sich als Frau und Künstlerin zu emanzipieren. Auch von Max Ernst.`,
    kategorie:"Romane",
    "ISBN/GTIN": "978-3-463-00001-5",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Kindler",
    Erscheinungsjahr:"2020",
    Erstverkaufstag:"18.08.2020",
    Gewicht:"555 g",
    ArtikelNr:"17730759",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Worlds Collide",
    autor : "Anabelle, Stehl",
    image: "https://www.kulturkaufhaus.de/annotstream/9783736316638/COPL/Stehl-Anabelle/Worlds-Collide.jpg?sq=22",
    preis :"12,90",
    sprache : "Deutsch",
    seiten : "576",
    beschreibung : `Wenn Welten aufeinanderprallen ...
    Fiona hat es geschafft: Sie ist eine der erfolgreichsten Beauty-YouTuber:innen Englands, reist von Event zu Event und wird schon bald eine eigene Make-up-Linie herausbringen. Aber ihr Leben war nicht immer glamourös. Aufgewachsen in einer finanziell schwachen Familie nutzt sie ihre Reichweite, um anderen zu helfen. Ihr gutes Image gerät ins Wanken, als YouTuber Demian einen Skandal aufdeckt, in den Fiona unfreiwillig verwickelt ist. Bei einer Convention will sie ihren guten Ruf retten ... doch dann sitzt bei einem Panel ausgerechnet Demian neben ihr.
    »Es hat nur wenige Seiten gebraucht, um mich in dieses Buch zu verlieben.« THE BOOK DYNASTY über BREAKAWAY
    Auftaktband der WORLDS-Reihe rund um junge Influencer:innen in London von SPIEGEL-Bestseller-Autorin Anabelle Stehl`,
    kategorie:"New Adult",
    "ISBN/GTIN": "978-3-7363-1663-8",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"LYX",
    Erscheinungsjahr:"2022",
    Erstverkaufstag:"17.03.2022",
    Gewicht:"",
    ArtikelNr:"19691382",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Step into my Heart",
    autor : "Maren Vivien, Haase",
    image: "https://www.kulturkaufhaus.de/annotstream/9783734110030/COPL/Haase-Maren-Vivien/Step-into-my-Heart.jpg?sq=3",
    preis :"13,00",
    sprache : "Deutsch",
    seiten : "464",
    beschreibung : `Olivia und Dax: Entgegen aller Widerstände wollen sie ihre Träume wahr werden lassen - doch manchmal kommen Gefühle dazwischen.
    Olivia lebt für Hip-Hop und arbeitet hart daran, als Bühnentänzerin Fuß zu fassen - auch wenn ihre Eltern sie lieber beim Jurastudium sehen würden. Als sie einen Job bei einer Konzert-Tour ergattert, scheint das der ersehnte Durchbruch zu sein. Doch der Choreograf ist ausgerechnet Dax, der nach einem tragischen Unfall seine eigene Karriere als Tänzer beenden musste und Olivias Kumpel Austin die Schuld daran gibt. Verbittert und wütend hatte Dax sich damals von der Clique im Move District zurückgezogen, und so liegt nun bei der gemeinsamen Arbeit wieder reichlich Spannung in der Luft. Doch bald wird deutlich, dass dabei nicht nur die Geschehnisse aus der Vergangenheit und der Erfolgsdruck eine Rolle spielen, sondern auch aufkeimende Gefühle ...`,
    kategorie:"New Adult",
    "ISBN/GTIN": "978-3-7341-1003-0",
    Produktart: "Taschenbuch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Blanvalet",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"15.11.2021",
    Gewicht:"513 g",
    ArtikelNr:"16412641",
    Genre:"Belletristik | Erzählende Literatur"
    },
    {titel: "Midnight Chronicles - Seelenband",
    autor : "Bianca, Iosivoni",
    image: "https://www.kulturkaufhaus.de/annotstream/9783736313491/COPL/Iosivoni-Bianca/Midnight-Chronicles---Seelenband.jpg?sq=27",
    preis :"14,90",
    sprache : "Deutsch",
    seiten : "464",
    beschreibung : `Sie will ihn nicht mehr lieben. Er will nichts anderes als sie zurückzugewinnen.
    Die Midnight Chronicles gehen weiter
    Ella hat am Tag des Blutbades alles verloren - und gibt sich selbst die Schuld daran. Als einziger Ausweg bleibt der Soul Huntress die Flucht nach Prag, weit weg von all dem, was sie quält. Doch dann steht ausgerechnet die eine Person wieder vor ihr, die sie mit allen Mitteln zu vergessen versucht: Wayne McKinley. Einst ihr süßestes Geheimnis, scheint Wayne nun nur noch eine schmerzvolle Erinnerung zu sein. Ella bleibt jedoch keine andere Wahl, als mit ihm zusammenzuarbeiten, um ihren Fehler vom Tag des Blutbades wiedergutzumachen. Auch auf die Gefahr hin, dass ihre Gefühle für den Hunter mit jeder gemeinsam verbrachten Minute stärker werden.
    "Dieses Buch hat mich mit allem, was es zu bieten hat, in den Bann gezogen und fassungslos zurückgelassen. Die Geschichte fesselt, das Setting fasziniert jedes Mal aufs Neue, und die Protagonisten muss man einfach lieben." BOOKWORMIII über DUNKELSPLITTER
    Band 4 der Reihe trägt den Titel SEELENBAND und erzählt die Geschichte von Ella und Wayne.`,
    kategorie:"New Adult",
    "ISBN/GTIN": "",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"LYX",
    Erscheinungsjahr:"2022",
    Erstverkaufstag:"23.02.2022",
    ArtikelNr:"16464508",
    Genre:"Belletristik | Science Fiction, Fantasy"
    },
    {titel: "Cassardim 3: Jenseits der Tanzenden Nebel",
    autor : "Julia, Dippel",
    image: "https://www.kulturkaufhaus.de/annotstream/9783522507226/COPL/Dippel-Julia/Cassardim-3-Jenseits-der-Tanzenden-Nebel.jpg?sq=4",
    preis :"17,00",
    sprache : "Deutsch",
    seiten : "464",
    beschreibung : `Der dritte und finale Band der Trilogie von Fantasy-Queen Julia DippelDer Kaiser ist tot, doch Amaias Status als Goldene Erbin ist nach wie vor umstritten. Sie steht zwischen der Tradition und einer Revolution - größer, als Cassardim sie je gesehen hat. Noár ist bemüht, sie aus der Schusslinie zu halten, aber Amaia verfolgt eigene Pläne. Sie muss das wachsende Chaos aufhalten, das von ihrem frisch vermählten Ehemann Besitz ergreift. Um ihn, Cassardim und die Menschenwelt zu retten, versammelt sie auf eigene Faust die Erben aller Reiche um sich und begibt sich mit ihnen auf die gefährliche Suche nach einem neuen Juwel der Macht. Ein Wettlauf gegen die Zeit beginnt, an dessen Ende sie nicht nur ihre große Liebe verlieren könnte ...`,
    kategorie:"New Adult",
    "ISBN/GTIN": "978-3-522-50722-6",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Planet! in der Thienemann-Esslinger Verlag GmbH",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"25.11.2021",
    Gewicht:"772 g",
    ArtikelNr:"19765904",
    Genre:"Kinder- und Jugendbücher"
    },
    {titel: "Words I Keep",
    autor : "Josi, Wismar",
    image: "https://www.kulturkaufhaus.de/annotstream/9783453425200/COPL/Wismar-Josi/Words-I-Keep.jpg?sq=4",
    preis :"13,00",
    sprache : "Deutsch",
    seiten : "400",
    beschreibung : `Es gibt Worte, an die man sich für immer erinnern möchte
    Die schüchterne Studentin und Buchbloggerin Emely lebt zusammen mit ihrer älteren Schwester Cassidy im wunderschönen Amber Falls in den Rocky Mountains. Cas, ihre Bookstagram-Community und ihre besten Freunde Lexie und Will sind für Em das Wichtigste im Leben. Als sie dem attraktiven, aber undurchschaubaren David begegnet, fühlt sie es sofort: die Aufregung des Neuen, das Knistern des ersten Verliebtseins. Jedes Mal, wenn sie sich begegnen, sprühen die Funken. Doch die Beziehung mit ihm verändert Em und treibt einen Keil zwischen sie und Cas. Kann er der Richtige sein, wenn er ihr Leben so durcheinanderbringt? Em muss sich entscheiden, oder sie verliert alles. Gibt es Happy Ends doch nur in Büchern und nicht im echten Leben?`,
    kategorie:"New Adult",
    "ISBN/GTIN": "978-3-453-42520-0",
    Produktart: "Taschenbuch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Heyne",
    Erscheinungsjahr:"2022",
    Erstverkaufstag:"10.01.2022",
    Gewicht:"529 g",
    ArtikelNr:"16415036",
    Genre:"Belletristik"
    },
    {titel: "Barbarotti und der schwermütige Busfahrer",
    autor : "Hakan, Nesser",
    image: "https://www.kulturkaufhaus.de/annotstream/9783442771424/COPL/Nesser-H%C3%A5kan/Barbarotti-und-der-schwerm%C3%BCtige-Busfahrer.jpg?sq=4",
    preis :"12,00",
    sprache : "Deutsch",
    seiten : "416",
    beschreibung : `Gegen Inspektor Barbarottis Polizeikollegin - und neue Lebensgefährtin - Eva Backman wird in Stockholm intern ermittelt. Sie musste bei einem Einsatz zur Schusswaffe greifen, um Schlimmeres zu verhindern, was für einen der Beteiligten allerdings böse endete. Um Abstand zu gewinnen, beschließen Barbarotti und Backman, sich in die herbstliche Abgeschiedenheit Gotlands zurückzuziehen. Doch die Ruhe ist trügerisch. Barbarottis kriminalistische Instinkte werden geweckt, als er in einem Fahrradfahrer jenen rätselhaften Busfahrer zu erkennen glaubt, der vor sechs Jahren Opfer eines Verbrechens wurde, ohne dass man seine Leiche je gefunden hätte ...`,
    kategorie:"Krimis & Thriller",
    "ISBN/GTIN": "978-3-442-77142-4",
    Produktart: "Taschenbuch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"btb",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"09.11.2021",
    Gewicht:"360 g",
    ArtikelNr:"19596098",
    Genre:"Belletristik | Spannung | Krimis, Thriller, Spionage"
    },
    {titel: "Rehragout-Rendezvous",
    autor : "Rita, Falk",
    image: "https://www.kulturkaufhaus.de/annotstream/9783423262736/COPL/Falk-Rita/Rehragout-Rendezvous.jpg?sq=42",
    preis :"16,95",
    sprache : "Deutsch",
    seiten : "304",
    beschreibung : `»Was gibt's zum Essen?«
    »Nix. Die Oma kocht nicht mehr.«
    Zefix! Was ist denn in die Eberhofer-Weiber gefahren? Die Oma beschließt nach gefühlten 2000 Kuchen und noch mehr Schweinsbraten, Semmelknödeln und Kraut, sich der häuslichen Pflichten zu entledigen - und fortan zu chillen. Ausgerechnet an Weihnachten! Und seit die Susi ihre Karriere als stellvertretende Bürgermeistern verfolgt, fühlt sich der Sex mit ihr im schicken Neubau für den Franz an, als hätten sie ihn gratis zu den Esszimmermöbeln dazu bekommen. Zu allem Übel wird dann auch noch der Steckenbiller Lenz vermisst. Der Franz soll gefälligst eine Vermisstenanzeige aufgeben, die Mooshammer Liesl befürchtet das Schlimmste. Nur: Eine Leiche ist weit und breit nicht in Sicht. Damit steht der Eberhofer vor einer schier unlösbaren Aufgabe.`,
    kategorie:"Krimis & Thriller",
    "ISBN/GTIN": "978-3-423-26273-6",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"DTV",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"17.09.2021",
    ArtikelNr:"17373617",
    Genre:"Belletristik | Spannung | Krimis, Thriller, Spionage"
    },
    {titel: "Rue de Paradis",
    autor : "Alexander, Oetker",
    image: "https://www.kulturkaufhaus.de/annotstream/9783455012125/COPL/Oetker-Alexander/Rue-de-Paradis.jpg?sq=7",
    preis :"16,00",
    sprache : "Deutsch",
    seiten : "288",
    beschreibung : `Die große Bestseller-Reihe geht weiter: In der Rue de Paradis, einer Straße zwischen Ozean und Austernbucht, gerät Luc Verlain in ein Dickicht aus Lügen, Neid und lange gehüteten Geheimnissen.
    Bei einer schweren Sturmflut wird in einem kleinen Ort auf der Halbinsel Cap Ferret eine ganze Straße Opfer der Wassermassen, auch eine alte Frau stirbt in jener Nacht. Tatsächlich hätte hier, in der Rue de Paradis, nie gebaut werden dürfen. Nun müssen alle Häuser weg und die Bewohner umgesiedelt werden, aus ihrem Idyll am Ende der Welt. Luc Verlain soll in der aufgeheizten Stimmung vermitteln und findet sich bald in seinem kniffligsten Fall wieder, genau in der Nacht, in der eine neue Sturmflut droht: Der Bürgermeister des Dorfes treibt tot im Wasser. War der Mord an ihm die Rache des Enkels der Toten aus der Sturmnacht? Oder ist einer der Menschen schuldig, deren Häuser abgerissen werden? Bald wird klar: Der reiche Politiker hatte nur noch Feinde in der Rue de Paradis.`,
    kategorie:"Krimis & Thriller",
    "ISBN/GTIN": "978-3-455-01212-5",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Hoffmann und Campe",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"01.11.2021",
    Gewicht:"389 g",
    ArtikelNr:"19648294",
    Genre:"Belletristik | Spannung | Krimis, Thriller, Spionage"
    },
    {titel: "Eifersucht",
    autor : "Jo, Nesbo",
    image: "https://www.kulturkaufhaus.de/annotstream/9783550201523/COPL/Nesb%C3%B8-Jo/Eifersucht.jpg?sq=4",
    preis :"22,99",
    sprache : "Deutsch",
    seiten : "272",
    beschreibung : `Der neue Coup von Jo Nesbø - Über 6 Millionen verkaufte Krimis im deutschsprachigen Raum
    "Der König des skandinavischen Kriminalromans" The Times
    Sieben erstklassige Stories, ein Motiv
    Der Athener Ermittler Nikos Balli, ein Spezialist für das Mord-Motiv Eifersucht, ist seit dem Verlust seiner großen Liebe ein Getriebener. Auf der Insel Kalymnos soll er einen Vermissten finden, Julian. Er und sein Zwillingsbruder Franz waren in dieselbe Frau verliebt, Helena, Tochter eines Gastwirts der Insel. Es kam zum Streit, und seitdem hat man Julian nicht mehr gesehen. Sein Handtuch wurde am Strand gefunden, ist der junge Mann beim morgendlichen Schwimmen ertrunken?
    Balli ermittelt und stößt auf immer mehr Beweise, dass Franz seinen Bruder ermordet hat - aber dann wird Julian gefunden, gefesselt und entkräftet in einer Höhle. Doch wo ist Franz? Balli muss all sein Gespür aufbringen, seine eigene schmerzvolle Erfahrung nochmals durchleben, um den Kampf der Zwillinge um Helena zu stoppen ...`,
    kategorie:"Krimis & Thriller",
    "ISBN/GTIN": "978-3-550-20152-3",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Ullstein HC",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"01.11.2021",
    Gewicht:"434 g",
    ArtikelNr:"19811084",
    Genre:"Belletristik | Spannung | Krimis, Thriller, Spionage"
    },
    {titel: "Die unhöfliche Tote",
    autor : "S. J., Bennett",
    image: "https://www.kulturkaufhaus.de/annotstream/9783426227411/COPL/Bennett-S.-J./Die-unh%C3%B6fliche-Tote.jpg?sq=10",
    preis :"18,00",
    sprache : "Deutsch",
    seiten : "368",
    beschreibung : `England hat eine neue Queen of Crime: Königin Elizabeth ermittelt höchstpersönlich!
    »Die unhöfliche Tote« ist der 2. Teil der humorvollen cosy Krimi-Reihe mit Queen Elizabeth als heimlicher Detektivin.
    Queen Elisabeth ist wirklich not amused über den Ausgang des Brexit-Referendums. Das Letzte, was sie jetzt gebrauchen kann, sind weitere Sorgen - wie zum Beispiel das Fehlen eines ihrer Lieblingsgemälde oder eine Leiche, die am Pool von Buckingham Palace liegt ...
    Die Tote war eine langjährige Haushälterin, und hartnäckige Gerüchte über deren Unbeliebtheit verlangen nach diskreten Nachforschungen. So lässt die Queen wieder einmal nur vordergründig die Polizei und ihre Offiziellen agieren, im Hintergrund aber setzt sie ihre kluge Assistentin Rozie und ihre eigenen grauen Zellen ein. Als sich herausstellt, dass im Hofstaat seit längerer Zeit Drohbriefe kursieren, nimmt der Fall eine bedenkliche Wendung. Und was geht eigentlich in den geheimen Tunneln unter Londons Königspalästen vor ...?
    Auch Teil 2 von S. J. Bennetts hinreißender Krimi-Reihe sprüht vor Charme und britischem Humor.
    Ihren ersten Fall lösen Queen Elisabeth und ihre Sekretärin Rozie im cleveren cosy Krimi »Das Windsor-Komplott«.`,
    kategorie:"Krimis & Thriller",
    "ISBN/GTIN": "978-3-426-22741-1",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Droemer/Knaur",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"02.11.2021",
    Gewicht:"495 g",
    ArtikelNr:"19602049",
    Genre:"Belletristik | Spannung | Krimis, Thriller, Spionage"
    },
    {titel: "Das Ministerium für die Zukunft",
    autor : "Kim Stanley, Robinson",
    image: "https://www.kulturkaufhaus.de/annotstream/9783453321700/COPL/Robinson-Kim-Stanley/Das-Ministerium-f%C3%BCr-die-Zukunft.jpg?sq=1",
    preis :"17,00",
    sprache : "Deutsch",
    seiten : "720",
    beschreibung : `Von Barack Obama auf Twitter empfohlen!
    Indien, 2025. Das Land wird von einer gnadenlosen Hitzewelle heimgesucht, die Temperaturen erreichen mancherorts über 50 Grad. Hunderttausende Menschen sterben, manchmal werden ganze Stadtviertel ausgelöscht. Zu den Überlebenden gehört der Entwicklungshelfer Frank May. Schwer traumatisiert zieht er in die Schweiz, um mit denen abzurechnen, die seiner Meinung nach mitverantwortlich sind: dem Ministerium für die Zukunft, dessen Aufgabe es eigentlich ist, solche Katastrophen zu verhindern. In Mary Murphy, der Vorsitzenden des Ministeriums, findet Frank unerwartet eine Verbündete, die wie er gegen den Klimawandel kämpft - wenn auch mit anderen Mitteln ...`,
    kategorie:"Fantasy & Sci-Fi",
    "ISBN/GTIN": "978-3-453-32170-0",
    Produktart: "Taschenbuch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Heyne",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"11.10.2021",
    Gewicht:"688 g",
    ArtikelNr:"16415021",
    Genre:"Belletristik | Science Fiction, Fantasy | Science Fiction"
    },
    {titel: "Snow Crash",
    autor : "Neal, Stephenson",
    image: "https://www.kulturkaufhaus.de/annotstream/9783596705597/COPL/Stephenson-Neal/Snow-Crash.jpg?sq=2",
    preis :"16,99",
    sprache : "Deutsch",
    seiten : "576",
    beschreibung : `Die Erfindung des Metaverse durch SF-Visionär Neal Stephenson.
    Visionär und rasend schnell erzählt: Das zentrale Werk des Cyberpunks jetzt in neuer Übersetzung.
    Hiro Protagonist war mal Programmierer, aber seit auch hier die Konzerne alles gleichgeschaltet haben, zieht er jeden Bullshit-Job vor: Pizza-Auslieferer für die Mafia. Oder Information Broker für die ehemalige CIA.
    Wichtiger als die echte Welt ist für ihn ohnehin das Metaverse, ein virtueller Ort, an dem sich die Menschen mit ihren selbst gestalteten Avataren treffen. Dort begegnet er auch zum ersten Mal der Droge »Snow Crash«. Das Besondere: Snow Crash ist ein Computervirus, der auch Menschen befallen kann. Zusammen mit seiner Partnerin Y. T. ermittelt Hiro - und kommt einer Verschwörung auf die Spur, die bis in die menschliche Vorgeschichte zurückreicht.
    Für Leserinnen von William Gibson, Richard Morgan und Fans von Cyberpunk 2077.`,
    kategorie:"Fantasy & Sci-Fi",
    "ISBN/GTIN": "978-3-596-70559-7",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"FISCHER Tor",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"27.10.2021",
    Gewicht:"533 g",
    ArtikelNr:"19766373",
    Genre:"Belletristik | Science Fiction, Fantasy | Science Fiction"
    },
    {titel: "Supernova",
    autor : "Cixin, Liu",
    image: "https://www.kulturkaufhaus.de/annotstream/9783453320314/COPL/Liu-Cixin/Supernova.jpg?sq=2",
    preis :"14,99",
    sprache : "Deutsch",
    seiten : "512",
    beschreibung : `Der letzte Tag der Menschheit ist angebrochen. Eine gewaltige Strahlenwolke, ausgelöst durch eine Sternexplosion acht Jahre zuvor, wird schon bald alle Menschen über dreizehn Jahren töten. Seit acht Jahren läuft der Countdown, und seitdem werden die Kinder und Jugendlichen der Welt auf eine Zukunft allein vorbereitet. Einige von ihnen jedoch wollen gar nicht so weitermachen wie zuvor. Sie träumen von einer neuen, einer besseren Zukunft für sich und ihren Planeten. Dies ist ihre Geschichte ...`,
    kategorie:"Fantasy & Sci-Fi",
    "ISBN/GTIN": "978-3-453-32031-4",
    Produktart: "Taschenbuch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Heyne",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"13.12.2021",
    Gewicht:"650 g",
    ArtikelNr:"18922370",
    Genre:"Belletristik | Science Fiction, Fantasy | Science Fiction"
    },
    {titel: "Outpost - Der Posten",
    autor : "Dmitry, Glukhovsky",
    image: "https://www.kulturkaufhaus.de/annotstream/9783453321779/COPL/Glukhovsky-Dmitry/Outpost---Der-Posten.jpg?sq=1",
    preis :"20,00",
    sprache : "Deutsch",
    seiten : "416",
    beschreibung : `Russland in der nahen Zukunft. Nach dem Krieg sind ganze Landstriche verseucht, die Flüsse vergiftet. Die einzelnen Städte haben kaum noch Kontakt zur Regierung in Moskau. Schon seit Jahren harrt Jegor im Außenposten in Jaroslawl aus. Sein Stiefvater Polkan, der Kommandant des Postens, macht ihm das Leben schwer, und die schöne Michelle interessiert sich nicht für ihn. Jegor träumt von der Welt jenseits der Eisenbahnbrücke, auf der anderen Seite des Flusses. Doch schon seit Jahrzehnten ist niemand mehr über diese Brücke gekommen. Bis heute ...`,
    kategorie:"Fantasy & Sci-Fi",
    "ISBN/GTIN": "978-3-453-32177-9",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Heyne",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"11.10.2021",
    Gewicht:"590 g",
    ArtikelNr:"19595665",
    Genre:"Belletristik | Science Fiction, Fantasy | Science Fiction"
    },
    {titel: "Algorytmica",
    autor : "Marion, Herzog",
    image: "https://www.kulturkaufhaus.de/annotstream/9783453424517/COPL/Herzog-Marion/Algorytmica.jpg?sq=1",
    preis :"16,00",
    sprache : "Deutsch",
    seiten : "432",
    beschreibung : `Wir schreiben das 24. Jahrhundert: Nach einer globalen Katastrophe haben sich die Überlebenden in riesige unterirdische Bunkeranlagen, sogenannte Archen, zurückgezogen. Dank hochmoderner Technologie und fähiger Programmierer sind die Arche-Bewohner vierundzwanzig Stunden am Tag in virtuelle Welten eingeloggt und können so vergessen, dass sie tief unter der Erdoberfläche in winzigen Zellen an lebenserhaltende Systeme angeschlossen sind. Dann kommt es eines Tages zu einem Black-out, die Systeme fallen aus und es wird klar, wie verletzlich die unterirdische Gesellschaft eigentlich ist. Die Informatikstudentin Kaja wittert eine Verschwörung, aber niemand nimmt sie ernst. Sie erhält jedoch Unterstützung von unerwarteter Seite: Liam Turner ist ein brillanter Kopf, der Verbindungen ins Darknet hat, und er glaubt Kaja. Und tatsächlich kommen die beiden einem gewaltigen Komplott auf die Spur ...`,
    kategorie:"Fantasy & Sci-Fi",
    "ISBN/GTIN": "978-3-453-42451-7",
    Produktart: "Taschenbuch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Heyne",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"13.12.2021",
    Gewicht:"564 g",
    ArtikelNr:"19596070",
    Genre:"Belletristik | Science Fiction, Fantasy | Science Fiction"
    },
    {titel: "Sensibel",
    autor : "Svenja, Flaßpöhler",
    image: "https://www.kulturkaufhaus.de/annotstream/9783608983357/COPL/Fla%C3%9Fp%C3%B6hler-Svenja/Sensibel.jpg?sq=6",
    preis :"20,00",
    sprache : "Deutsch",
    seiten : "240",
    beschreibung : `»Sensibilität ist eine zivilisatorische Errungenschaft. Im Kampf um Anerkennung unterdrückter Gruppen spielt sie eine wichtige Rolle. Aber sie kann auch vom Progressiven ins Regressive kippen. Über diese Dialektik müssen wir nachdenken, um die gesellschaftliche Polarisierung zu überwinden.«
    Svenja Flaßpöhler
    Mehr denn je sind wir damit beschäftigt, das Limit des Zumutbaren neu zu justieren. Wo liegt die Grenze des Sagbaren? Ab wann ist eine Berührung eine Belästigung? Svenja Flaßpöhler tritt einen Schritt zurück und beleuchtet den Glutkern des Konflikts: die zunehmende Sensibilisierung des Selbst und der Gesellschaft.
    Menschheitsgeschichtlich steht die Sensibilisierung für Fortschritt: Menschen schützen sich wechselseitig in ihrer Verletzlichkeit, werden empfänglicher für eigene und fremde Gefühle, lernen, sich in fremde Schicksale hineinzuversetzen und mit anderen zu solidarisieren. Doch diese Entwicklung hat eine Kehrseite: Anstatt uns zu verbinden, zersplittert die Sensibilität die Gesellschaft. Erleben wir gerade den Kipppunkt fortschreitender Sensibilisierung? Svenja Flaßpöhler erzählt die Geschichte des sensiblen Selbst aus philosophischer Perspektive, beleuchtet die zentralen Streitfragen der Zeit und arbeitet den Grund für die prekäre Schieflage heraus: Weil die Widerstandskraft bis heute mit kalter Verpanzerung assoziiert wird, gilt sie als Feindin der Sensibilität. Aber stimmt das? »Sensibel« ist ein hochaktuelles, philosophisches und gleichzeitig unterhaltsames Buch, das die Sensibilität dialektisch durchleuchtet und zu dem Schluss kommt: Die Resilienz ist die Schwester der Sensibilität. Die Zukunft meistern können sie nur gemeinsam.`,
    kategorie:"Sachbücher & Ratgeber",
    "ISBN/GTIN": "978-3-608-98335-7",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Klett-Cotta",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"20.10.2021",
    Gewicht:"330 g",
    ArtikelNr:"19602392",
    Genre:"Sachbuch | Politik, Gesellschaft, Wirtschaft | Gesellschaft"
    },
    {titel: "Nachruf auf mich selbst.",
    autor : "Harald, Welzer",
    image: "https://www.kulturkaufhaus.de/annotstream/9783103971033/COPL/Welzer-Harald/Nachruf-auf-mich-selbst..jpg?sq=4",
    preis :"22,00",
    sprache : "Deutsch",
    seiten : "288",
    beschreibung : `Bestseller-Autor Harald Welzer stellt fest, dass unsere Kultur kein Konzept vom Aufhören hat. Deshalb baut sie Autobahnen und Flughäfen für Zukünfte, in denen es keine Autos und Flughäfen mehr geben wird. Und sie versucht, unsere Zukunftsprobleme durch Optimierung zu lösen, obwohl ein optimiertes Falsches immer noch falsch ist. Damit verbaut sie viele Möglichkeiten, das Leben durch Weglassen und Aufhören besser zu machen. Diese Kultur hat den Tod genauso zur Privatangelegenheit gemacht, wie sie die Begrenztheit der Erde verbissen ignoriert.
    Harald Welzer zeigt in einer faszinierenden Montage aus wissenschaftlichen Befunden, psychologischen Einsichten und persönlichen Geschichten, wie man aus den Absurditäten dieser gesellschaftlichen Entwicklung herausfindet. Man muss rechtzeitig einen Nachruf auf sich selbst schreiben, damit man weiß, wie man gelebt haben will.`,
    kategorie:"Sachbücher & Ratgeber",
    "ISBN/GTIN": "978-3-10-397103-3",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"S.Fischer Verlag GmbH",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"06.10.2021",
    Gewicht:"405 g",
    ArtikelNr:"19766438",
    Genre:"Sachbuch | Politik, Gesellschaft, Wirtschaft | Gesellschaft"
    },
    {titel: "Hier gehts lang - das ist dran! Klasse 7-10",
    autor : "Corinne, Keller",
    image: "https://www.kulturkaufhaus.de/annotstream/2244000318484/COPL/Keller-Corinne/Hier-gehts-lang---das-ist-dran-Klasse-7-10.jpg?sq=15",
    preis :"13,99",
    sprache : "Deutsch",
    beschreibung : `Als Lehrer kennen Sie Momente wie diese: Sie möchten, dass Ihre Schüler ohne Diskussionen in unterschiedlichen Gruppen gut zusammenarbeiten, im Klassenrat problemlos bestimmte Aufgaben übernehmen und dass im Klassenzimmer eine konstruktive Arbeitsatmosphäre herrscht. Im Schulalltag werden diese wiederkehrenden Situationen oft verbal gelöst. Aber das ständige Reden geht auf die Stimme und verhallt gelegentlich ungehört in Schülerohren. Daher finden Sie hier eine Fülle von Karten und Schildern, mit denen Sie ihren täglichen Unterricht effektiv und stimmschonend strukturieren können. Nach dem Motto "Bilder sagen mehr als 1000 Worte" sehen Ihre Schüler sofort und unmissverständlich, wer zu welcher Gruppe gehört, wer auf die Einhaltung der Klassenratsregeln achtet oder ob der Lärmpegel so akzeptabel ist. Die Illustrationen sind auf Schüler im Alter von ca. 13 bis 16 Jahren abgestimmt.`,
    kategorie:"Sachbücher & Ratgeber",
    "ISBN/GTIN": "9783403402107",
    Produktart: "E-Book" ,
    Einbandart:"Electronic Book",
    Verlag:"AOL-Verlag",
    Erscheinungsjahr:"2011",
    Erstverkaufstag:"01.02.2011",
    Dateigroesse:"5891 Kbytes",
    ArtikelNr:"2533083",
    Genre:"Schule und Lernen"
    },
    {titel: "Entscheidungstage",
    autor : "Stephan, Lamby",
    image: "https://www.kulturkaufhaus.de/annotstream/9783406774331/COPL/Lamby-Stephan/Entscheidungstage.jpg?sq=23",
    preis :"22,00",
    sprache : "Deutsch",
    seiten : "382",
    beschreibung : `DIE NERVENSCHLACHT UMS KANZLERAMT
    Deutschland erlebt dramatische politische Veränderungen. Nach einem Wahljahr mit zahlreichen Richtungswechseln wird die Parteienlandschaft durch die Bundestagswahl kräftig umgepflügt. Es gibt überraschende Aufstiege und schmerzhafte Abstürze. Aber es geht um weit mehr als um einzelne Karrieren. Die künftige Regierung steht vor immensen Herausforderungen - wegen des Klimawandels, der Pandemie, des gewaltigen Reformstaus, auch wegen des Auseinanderdriftens der Gesellschaft.
    Stephan Lamby untersucht das politische Leben in Deutschland seit einem Vierteljahrhundert. Seine Langzeitbeobachtungen dauern monate-, manchmal jahrelang. Seit Dezember 2020 hat er sich auf die Spuren der drei Kanzlerkandidat:innen begeben. Er konnte hinter die Kulissen der Kampagnen von SPD, Union und Grünen blicken, mit Olaf Scholz, Armin Laschet, Annalena Baerbock, Robert Habeck und ihren Wahlkampfmanagern viele exklusive Gespräche führen und sie aus der Nähe beobachten. Auch mit Christian Lindner, Markus Söder und vielen anderen sprach er ausführlich. Lamby erlebte hautnah mit, wie das Momentum beim Kampf ums Kanzleramt schlagartig hin und her wechselte - und lernte das Personal verstehen, das Deutschland in den nächsten Jahren führen wird. Sein Buch erklärt, wie es zu diesem ungewöhnlichen Bundestagswahlergebnis kommen konnte. Lamby blickt dabei auch auf frühere Kampagnen und Wahlkämpfer zurück, die er ebenfalls aus der Nähe beobachtete: von Kohl über Merkel bis Steinbrück und Schulz. Seine investigative Reportage ist nicht nur die fällige Chronik einer epischen Entscheidungsschlacht, sondern auch eine zeitlose Anatomie von Machtmenschen unter äußerster Anspannung.
    Machtkampf hautnah - ein Blick hinter die Kulissen der deutschen Spitzenpolitik
    Der Autor hat exklusiv alle drei Kanzlerkandidat:innen begleitet
    Vom renommierten Langzeitbeobachter der deutschen Spitzenpolitik und «Journalist des Jahres» 2018`,
    kategorie:"Sachbücher & Ratgeber",
    "ISBN/GTIN": "978-3-406-77433-1",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Beck",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"25.10.2021",
    Gewicht:"618 g",
    ArtikelNr:"20420874",
    Genre:"Sachbuch | Politik, Gesellschaft, Wirtschaft | Politik"
    },
    {titel: "1000 Jahre Freud und Leid",
    autor : "Weiwei, Ai",
    image: "https://www.kulturkaufhaus.de/annotstream/9783328602316/COPL/Ai-Weiwei/1000-Jahre-Freud-und-Leid.jpg?sq=4",
    preis :"38,00",
    sprache : "Deutsch",
    seiten : "416",
    beschreibung : `Einer der größten Künstler unserer Zeit erzählt sein Leben vor dem Hintergrund der Geschichte Chinas
    Ai Weiwei gehört zu den bekanntesten Künstlern unserer Zeit. In »1000 Jahre Freud und Leid« schildert er erstmals seinen außerordentlichen künstlerischen Werdegang vor dem Hintergrund der Geschichte seiner Familie in China. Schon als Junge erlebte er die Verbannung und Demütigung seines Vaters Ai Qing, einst ein Vertrauter Maos und Chinas einflussreichster Dichter, der im Zuge der Kulturrevolution als »Rechtsabweichler« gebrandmarkt wurde. Diese Erfahrungen prägten Ai Weiweis Schaffen und seine politischen Überzeugungen. Er beschreibt die schwierige Entscheidung, seine Familie zu verlassen, um für ein Kunststudium in die USA zu gehen, wo er sich u. a. mit Allen Ginsberg anfreundete und künstlerische Inspiration fand. Offen erzählt er von seinem Aufstieg zu einem Star der internationalen Kunstwelt, der aufgrund seiner Menschenrechtsaktivitäten jedoch immer stärker ins Visier des chinesischen Regimes geriet, das ihn schließlich 2011 mehrere Monate inhaftierte. Die sehr persönlichen und vom Künstler selbst reich illustrierten Erinnerungen geben nicht nur einen fesselnden Einblick in Ai Weiweis Leben und Arbeiten, sie sind zugleich Mahnung, die Meinungsfreiheit immer wieder neu zu verteidigen.`,
    kategorie:"Sachbücher & Ratgeber",
    "ISBN/GTIN": "978-3-328-60231-6",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Penguin Verlag München",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"02.11.2021",
    Gewicht:"732 g",
    ArtikelNr:"16417108",
    Genre:"Sachbuch | Politik, Gesellschaft, Wirtschaft"
    },
    {titel: "Die Hüterin der Drachen",
    autor : "Curatoria, Draconis",
    image: "https://www.kulturkaufhaus.de/annotstream/9783791374833/COPL/Draconis-Curatoria/Die-H%C3%BCterin-der-Drachen.jpg?sq=3",
    preis :"26,00",
    sprache : "Deutsch",
    seiten : "80",
    beschreibung : `Der ultimative Drachen-Führer: Geheimnisvolle Drachen und wo sie zu finden sind
    Willkommen auf der Drachen-Arche!`,
    kategorie:"Kinder- und Jugendbücher",
    "ISBN/GTIN": "978-3-7913-7483-3",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Prestel",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"20.09.2021",
    Gewicht:"989 g",
    ArtikelNr:"19596035",
    Genre:"Kinder- und Jugendbücher | Sachbücher, Sachbilderbücher"
    },
    {titel: "You will be the death of me",
    autor : "Karen M., McManus",
    image: "https://www.kulturkaufhaus.de/annotstream/9783570166062/COPL/McManus-Karen-M./You-will-be-the-death-of-me.jpg?sq=6",
    preis :"20,00",
    sprache : "Deutsch",
    seiten : "416",
    beschreibung : `Drei ehemalige Freunde. Ein Zufallstreffen. Ein Mord.
    Ivy, Mateo und Cal waren einmal befreundet, jetzt haben sie nichts mehr miteinander gemein. Aber als Cal zu spät zur Schule kommt und dort auf Ivy und Mateo trifft, scheint das die Gelegenheit zu sein, eine alte Tradition wiederaufleben zu lassen: einen Tag blau machen. Bei ihrem spontanen Ausflug in die Stadt sichten sie einen vierten Schüler auf Abwegen und folgen ihm - mitten hinein in einen Tatort. Ivy, Cal und Mateo kennen den Toten, der vor ihnen liegt - und eigentlich sollten sie jetzt die Polizei rufen. Doch sie alle haben eine Verbindung zu dem Toten. Und etwas zu verbergen. War ihr Zufallstreffen wirklich ein Zufall?`,
    kategorie:"Kinder- und Jugendbücher",
    "ISBN/GTIN": "978-3-570-16606-2",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"cbj",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"13.12.2021",
    Gewicht:"580 g",
    ArtikelNr:"20346206",
    Genre:"Kinder- und Jugendbücher | Jugendbücher"
    },
    {titel: "Alea Aquarius 7. Im Bannkreis des Schwurs",
    autor : "Tanya, Stewner",
    image: "https://www.kulturkaufhaus.de/annotstream/9783751201698/COPL/Stewner-Tanya/Alea-Aquarius-7.-Im-Bannkreis-des-Schwurs.jpg?sq=4",
    preis :"18,00",
    sprache : "Deutsch",
    seiten : "464",
    beschreibung : `Liebe, Freundschaft, Abenteuer - und Sehnsucht nach einem Wiedersehen: Der siebte Band von Alea Aquarius! Diesmal machen sich Alea und Lennox über Land auf den Weg zum Loreley-Felsen. Dort vermuten die beiden Aleas Zwillingsschwester Anthea. Werden die Zwillinge sich tatsächlich endlich treffen? Und wird es dadurch gelingen, Aleas Meermädchen-Fähigkeiten zu reaktivieren?`,
    kategorie:"Kinder- und Jugendbücher",
    "ISBN/GTIN": "978-3-7512-0169-8",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Oetinger",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"29.09.2021",
    Gewicht:"754 g",
    ArtikelNr:"19436457",
    Genre:"Kinder- und Jugendbücher | Kinderbücher"
    },
    {titel: "Die Kackwurstfabrik",
    autor : "Marja, Baseler",
    image: "https://www.kulturkaufhaus.de/annotstream/9783954701889/COPL/Baseler-Marja/Die-Kackwurstfabrik.jpg?sq=3",
    preis :"15,00",
    sprache : "Deutsch",
    seiten : "48",
    beschreibung : `Unser Körper ist eine faszinierende Kackwurstfabrik auf zwei Beinen. Zusammen mit den Kindern Pim und Polly machen wir einen Rundgang durch diese Fabrik - vom Kontrollraum ganz oben über das Säurebad des Magens und die achterbahnartige Fahrt durch den Darm bis hinunter zu den Pförtnern des Enddarms. Wegen Überlastung und Verstopfung steht die Kackwurstfabrik allerdings kurz vor dem Aus. Pim und Polly sind fest entschlossen, sie zu retten.Am Bild einer Fabrik mit all ihren Abteilungen und Maschinen wird hier mit vielen lustigen Wimmelbildern und Info-Kästen erklärt, was bei der Verdauung passiert.Vom Bissen im Mund bis zur Wurst im Klo - eine spannende Werkbesichtigung unseres Verdauungsapparats`,
    kategorie:"Kinder- und Jugendbücher",
    "ISBN/GTIN": "978-3-95470-188-9",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Klett Kinderbuch Verlag",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"06.12.2021",
    ArtikelNr:"1907256",
    Genre:"Kinder- und Jugendbücher"
    },
    {titel: "Book Rebels",
    autor : "Annette, Pehnt",
    image: "https://www.kulturkaufhaus.de/annotstream/9783446271326/COPL/Pehnt-Annette/Book-Rebels.jpg?sq=2",
    preis :"22,00",
    sprache : "Deutsch",
    seiten : "192",
    beschreibung : `Von Iphigenie über Pippi Langstrumpf bis zu Meggie aus "Tintenherz": "Book Rebels" versammelt 75 literarische Heldinnen aus unterschiedlichen Zeiten - zum Entdecken und Schmökern.Diese Frauen- und Mädchenfiguren aus der Literatur sind wahre Rebellinnen. Sie sind stark, beweisen Mut und gehen ihre eigenen Wege. Sie stehen zu ihren Schwächen, müssen gegen Rückschläge kämpfen und lassen sich dennoch nicht unterkriegen. Ihre Geschichten kann man in Büchern nachlesen. In einzigartigen Porträts werden diese literarischen Heldinnen vorgestellt: Von Iphigenie über Alice, Heidi und Pippi bis hin zu Katniss und Starr versammelt dieses Buch 75 außergewöhnliche Mädchen und Frauen aus unterschiedlichen Epochen und Kulturen. Eine inspirierende Lektüre zum Entdecken und Schmökern, eindrucksvoll illustriert von Felicitas Horstschäfer.`,
    kategorie:"Kinder- und Jugendbücher",
    "ISBN/GTIN": "978-3-446-27132-6",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Hanser",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"25.10.2021",
    Gewicht:"617 g",
    ArtikelNr:"16414404",
    Genre:"16414404"
    },
    {titel: "Shelter",
    autor : "Ursula, Poznanski",
    image: "https://www.kulturkaufhaus.de/annotstream/9783743200517/COPL/Poznanski-Ursula/Shelter.jpg?sq=2",
    preis :"19,95",
    sprache : "Deutsch",
    seiten : "432",
    beschreibung : `Die Idee war völlig verrückt und sie wären niemals darauf gekommen, wenn die Party nicht so aus dem Ruder gelaufen wäre. Aus einer Katerlaune heraus erfinden Benny und seine Freunde eine irre Geschichte über außerirdische Besucher und verbreiten sie im Internet. Gespannt wartet die Clique ab, was passiert. Zu ihrer eigenen Überraschung nehmen immer mehr Menschen die Sache für bare Münze und Bennys Versuche, alles aufzuklären, bringen ihn schon bald in Lebensgefahr.
    Was, wenn du dir eine völlig absurde Geschichte ausdenkst, sie zum Spaß in die Welt setzt und plötzlich glauben alle daran? Ein schockierender Thriller über einen Streich, der zur verwirrenden Realität wird.
    Ursula Poznanskis neuer und hochaktueller Bestseller ist eine wache Analyse der Mechanismen moderner Verschwörungstheorien und ihrer Auswirkungen.`,
    kategorie:"Jugendbücher",
    "ISBN/GTIN": "978-3-7432-0051-7",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Loewe Verlag",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"13.10.2021",
    Gewicht:"648 g",
    ArtikelNr:"19888573",
    Genre:"Kinder- und Jugendbücher"
    },
    {titel: "Das Reich der sieben Höfe - Dornen und Rosen",
    autor : "Sarah J., Maas",
    image: "https://www.kulturkaufhaus.de/annotstream/9783423718493/COPL/Maas-Sarah-J./Das-Reich-der-sieben-H%C3%B6fe---Dornen-und-Rosen.jpg?sq=8",
    preis :"11,95",
    sprache : "Deutsch",
    seiten : "480",
    beschreibung : `Sie hat ein Leben genommen. Jetzt muss sie mit ihrem Herz dafür bezahlen.
    Die junge Jägerin Feyre wird in das sagenumwobene Reich der Fae entführt. Nichts ist dort, wie es scheint. Sicher ist nur eins: Sie muss einen Weg finden, um ihre Liebe zu retten. Oder ihre ganze Welt ist verloren.`,
    kategorie:"Jugendbücher",
    "ISBN/GTIN": "978-3-423-71849-3",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"DTV",
    Erscheinungsjahr:"2020",
    Erstverkaufstag:"22.05.2020",
    ArtikelNr:"16491439",
    Genre:"Kinder- und Jugendbücher"
    },
    {titel: "Das Reich der sieben Höfe - Silbernes Feuer",
    autor : "Sarah J., Maas",
    image: "https://www.kulturkaufhaus.de/annotstream/9783423763349/COPL/Maas-Sarah-J./Das-Reich-der-sieben-H%C3%B6fe---Silbernes-Feuer.jpg?sq=39",
    preis :"21,00",
    sprache : "Deutsch",
    seiten : "816",
    beschreibung : `Nesta und Cassian: Das neue Traumpaar am Fantasyhimmel
    Feyres Schwester Nesta war schon immer stolz, wütend und nachtragend - und seit sie gegen ihren Willen eine High Fae wurde, fällt es ihr schwer, ihren Platz am Hof der Nacht zu finden. Ausgerechnet Cassian soll Nesta nun dabei helfen, ihr Schicksal zu akzeptieren. Doch die plötzliche Nähe zu ihm stellt Nesta vor eine beinahe unerträgliche Herausforderung, denn noch immer kann und will sie ihren Gefühlen für Cassian nicht nachgeben.
    Als dem Reich der Fae erneut ein Krieg droht, liegt es an Nesta, drei magische Artefakte zu finden - um das Schlimmste zu verhindern. Doch die Suche bringt nicht nur dunkle Machenschaften ans Licht, sondern auch Nestas magische Fähigkeiten, die eine ungeahnte Gefahr darstellen ...
    Alte Gefährten, neue Freunde und noch gefährlichere Feinde - der neue Roman von Bestsellerautorin Sarah J. Maas ist mitreißender, leidenschaftlicher und magischer denn je!
    Kennen Sie bereits die weiteren Serien von Sarah J. Maas bei dtv?
    »Throne of Glass«
    »Crescent City«`,
    kategorie:"Jugendbücher",
    "ISBN/GTIN": "978-3-423-76334-9",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"DTV",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"20.10.2021",
    ArtikelNr:"19392179",
    Genre:"Kinder- und Jugendbücher"
    },
    {titel: "Das offizielle Harry Potter Koch- und Backbuch für Partys und Feste mit Rezepten und Kreativ-Ideen aus der Zauberwelt,",
    autor : "Jennifer, Carroll",
    image: "https://www.kulturkaufhaus.de/annotstream/9783845514307/COPL/Carroll-Jennifer/Das-offizielle-Harry-Potter-Koch--und-Backbuch-f%C3%BCr-Partys-und-Feste-mit-Rezepten-und-Kreativ-Ideen-aus-der-Zauberwelt.jpg?sq=5",
    preis :"28,00",
    sprache : "Deutsch",
    seiten : "192",
    beschreibung : `Jede Veranstaltung wird einfach magisch, wenn sie von der geheimnisvollen Zaubererwelt der Harry-Potter-Filme inspiriert ist!
    Und schon beim Lesen und Anschauen dieses umfangreichen, liebevoll gestalteten Handbuches steigt einem förmlich der Duft köstlicher Speisen in die Nase ...
    Mit diesem Werk können nun auch Muggel in den kulinarischen Kosmos von Harry, Hermine und Ron eintauchen, denn es enthält alles, um eine perfekte Party zum Thema Harry Potter zu planen und zauberhafte Feste zu organisieren: Rund 200 köstliche Rezepte, Bastelanregungen und Tipps zu Dekorationen, Einladungen und Spielen machen dieses opulente Buch zum Standardwerk jedes Fans. Gespickt mit zahlreichen Fotos, zauberhalten Abbildungen und lustigen Fakten sowie Einblicken hinter die Kulissen der Filme, bietet dieser umfassende Leitfaden eine Schritt-für-Schritt-Anleitung, wie man die perfekte Harry-Potter-Party organisiert.
    Der erste Teil konzentriert sich auf die Menüs und enthält über fünfzig Rezepte für festliche Speisen und Getränke, die auch die Herzen von Magiern und Hexen höher schlagen lassen, wenn sich in der großen Halle von Hogwarts die Tische wie von Zauberhand decken. Die herzhaften und süßen Kreationen greifen Figuren, Kreaturen, Artefakte und Orte aus den Filmen auf und beinhalten auch vegane, vegetarische, gluten- sowie zuckerfreie Optionen. Von Hogwarts speziellen Haus-Wraps bis hin zu Hagrids Happy-Birthday-Cupcakes werden alle Wünsche erfüllt.
    Teil zwei konzentriert sich auf die Planung und enthält Entwürfe für sechs Veranstaltungen zum Thema Zauberer, von einer Geburtstagsfeier mit buntem Hausmotto bis hin zu einer Halloween-Party im Verbotenen Wald. Jede Party enthält eine komplette Planungsstrategie sowie Ideen, Fotos und Anleitungen für Dekorationen, Einladungen, besondere Details, Aktivitäten und mehr.
    Viele Projekte enthalten außerdem kostenlos herunterladbare Vorlagen, die auf den Originalgrafiken aus den Filmen basieren.
    Dieses Buch macht Appetit aufs Feiern, welche Art von Fest Sie auch planen! Auch wenn Sie einfach nur Gäste oder Familie mit leckeren Koch- oder Backrezepten verwöhnen möchten - dieses Buch enthält alles, was Sie brauchen, damit Ihre nächste Veranstaltung so magisch wie eine Reise nach Hogwarts wird!
    Ein Muss für alle Harry Potter-Fans: Rund 200 Tipps für leckere Gerichte, Basteltipps und Anregungen für unvergessliche Feste! köstliche Koch- und Backrezepte - inspiriert von den reich gedeckten Tafeln in Hogwarts opulentes Standardwerk für alle Muggel, die in die geheimnisvolle Zaubererwelt eintauchen möchten`,
    kategorie:"Jugendbücher",
    "ISBN/GTIN": "978-3-8455-1430-7",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Nelson",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"29.11.2021",
    Gewicht:"1077 g",
    ArtikelNr:"19761482",
    Genre:"Kinder- und Jugendbücher"
    },
    {titel: "One Of The Good Ones",
    autor : "Maritza, Moulite",
    image: "https://www.kulturkaufhaus.de/annotstream/9783743211551/COPL/Moulite-Maritza/One-Of-The-Good-Ones.jpg?sq=1",
    preis :"14,95",
    sprache : "Deutsch",
    seiten : "416",
    beschreibung : `"Sie war doch eine von den Guten"
    Ausgerechnet Kezi! Happis große, hübsche, starke und kluge Schwester ist tot. Kezi hatte sich aktiv auf ihrem Youtube-Kanal für die Rechte Schwarzer Menschen eingesetzt. Und nun wurde sie selbst ein Opfer von Polizeigewalt nach einer Demonstration.
    Voller Trauer begibt sich Happi zusammen mit Freunden auf eine Reise, die noch von Kezi geplant worden ist. Quer durch die USA folgen sie dem Green Book, einem Reiseführer, der Schwarzen Reisenden während der Zeit der Rassentrennung angab, wo sie unbehelligt tanken, essen oder übernachten konnten.
    Kezi war eine "von den Guten", sagen die Leute. Aber ist ihr Tod deshalb besonders tragisch? Und was heißt das überhaupt?
    One of The Good Ones ist ein spannender Roadtrip durch das alte und neue Amerika und bricht auf unerwartete Weise mit allen unseren Erwartungen.
    Eine aufregende Reise durch die jüngere Geschichte der USA aus der Perspektive der afroamerikanischen Minderheit und ein begeisterndes Plädoyer für das Empowerment Schwarzer Menschen.`,
    kategorie:"Jugendbücher",
    "ISBN/GTIN": "978-3-7432-1155-1",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Loewe Verlag",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"17.11.2021",
    Gewicht:"503 g",
    ArtikelNr:"19890064",
    Genre:"Kinder- und Jugendbücher"
    },
    {titel: "Asterix 39",
    autor : "Jean-Yves, Ferri",
    image: "https://www.kulturkaufhaus.de/annotstream/9783770424399/COPL/Ferri-Jean-Yves/Asterix-39.jpg?sq=10",
    preis :"12,00",
    sprache : "Deutsch",
    seiten : "48",
    beschreibung : `Mit "Asterix und der Greif" legt das Duo Jean-Yves Ferri und Didier Conrad sein fünftes gemeinsames Asterix-Album vor! Diesmal verschlägt es die Gallier ins Barbaricum, weit im wilden Osten.Nach einem verheißungsvollen Traum macht sich Miraculix mit Asterix, Obelix und Idefix auf die Reise ins Land der Sarmaten. Dort wohnt der Schamane Terrine mitsamt seinem Stamm und hat die Hilfe seines alten Freundes bitter nötig!Denn die Römer sind auf dem Vormarsch, um für Cäsar den sagenumwobenen Greif zu fangen, der in dieser Region hausen soll. Zu allem Übel ist in der eisigen Kälte der Taiga auch noch Miraculix' Zaubertrank gefroren und dadurch unbrauchbar geworden...`,
    kategorie:"Comics & Manga",
    "ISBN/GTIN": "978-3-7704-2439-9",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Ehapa Comic Collection",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"21.10.2021",
    Gewicht:"364 g",
    ArtikelNr:"16408235",
    Genre:"Belletristik | Comic, Cartoon, Humor, Satire"
    },
    {titel: "Im Spiegelsaal",
    autor : "Liv, Strömquist",
    image: "https://www.kulturkaufhaus.de/annotstream/9783964450623/COPL/Str%C3%B6mquist-Liv/Im-Spiegelsaal.jpg?sq=1",
    preis :"20,00",
    sprache : "Deutsch",
    seiten : "168",
    beschreibung : `Bereits 2003 schrieb die Philosophin Susan Bordo, dass wir in einem "Imperium der Bilder" leben. In den letzten Jahren wurde diese Theorie mehr und mehr zur Realität: Eine iPhone-Kamera in jeder Hand, und dank der weit verbreiteten Social-Media-Nutzung ertrinken wir in einer Flut der Bilder. Wir kommunizieren durch Bilder, wir verabreden uns mittels Bildern, wir berichten aus unserem Leben mit Bildern und wir erfahren über das Leben anderer durch Bilder.Wie hat sich unser Schönheitsempfinden dadurch verändert? Diese Frage wird hier in fünf Essays, die sich dem Thema jeweils aus einer anderen Perspektive nähern, untersucht. Die Schwedin Liv Strömquist ist ein Phänomen. Ihre augenzwinkernden, minutiös recherchierten Sachcomics gehören zu den meist verkauften Graphic Novels weltweit."Liv Strömquist entzaubert nicht nur Sexualität, sondern auch das Patriarchat. Und das tut sie auf sehr schlaue, lustige und schöne Art". Margarete Stokowski`,
    kategorie:"Comics & Manga",
    "ISBN/GTIN": "978-3-96445-062-3",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"avant-verlag",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"26.10.2021",
    ArtikelNr:"19897159",
    Genre:"Belletristik | Comic, Cartoon, Humor, Satire"
    },
    {titel: "Es kann nur eine geben",
    autor : "Carolin, Kebekus",
    image: "https://www.kulturkaufhaus.de/annotstream/9783462001747/COPL/Kebekus-Carolin/Es-kann-nur-eine-geben.jpg?sq=3",
    preis :"18,00",
    sprache : "Deutsch",
    seiten : "352",
    beschreibung : `»Ich will den Finger in die Wunde legen!« Carolin Kebekus über Frauen an der Spitze.
    Eigentlich klingt es ganz leicht: Frau ist begabt und klug, also kann sie es schaffen, ganz nach oben zu kommen. Aber oft genug ist der eine Platz schon besetzt, es scheint nämlich ein höchst dämliches Gesetz zu geben, das lautet: Eine Frau reicht, mehr brauchen wir nicht. Die große Komikerin, Sängerin, Schauspielerin und Feministin schreibt pointiert, unmissverständlich und gleichzeitig wahnsinnig komisch, dass die Zeit überreif ist, alte (Männer-)Gesetze auf den Müll zu werfen.
    Wohin man auch schaut, immer ist es die eine Frau, die sich durchsetzt. In der Bibel ist es die jungfräuliche Maria, damit fing das Unheil an. Im Märchen gibt es immer die eine Prinzessin, sehr schön und sehr blöd. Die sündige Eva aus der Bibel und die böse Stiefmutter oder Hexe lassen wir mal hübsch beiseite, denn die sollen nur als Beispiele dafür dienen, was passiert, wenn Frauen nach Macht streben: Sie werden aus dem Paradies geworfen oder verbrannt. Mit dieser Prägung entlässt man Frauen ins Leben und wundert sich dann über die ständige Konkurrenz unter Frauen um diese begrenzten Plätze. Dann wird so getan, als wären Frauen von Natur aus eben stutenbissig und selbst schuld an dieser Rivalität. Carolin Kebekus kommt diesem bösen Spuk auf die Spur, sie untersucht alte und neue Geschichten, um zu zeigen, warum uns Frauen eingetrichtert wird, dass wir um den einen Platz - im Fernsehen, in der Firma, im Karneval usw. - konkurrieren müssten.
    Ein Buch von höchster Wichtigkeit, das aufklärt und gleichzeitig unterhält.`,
    kategorie:"Comics & Manga",
    "ISBN/GTIN": "978-3-462-00174-7",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"Kiepenheuer & Witsch",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"07.10.2021",
    Gewicht:"436 g",
    ArtikelNr:"19895616",
    Genre:"Belletristik | Comic, Cartoon, Humor, Satire"
    },
    {titel: "Starman - David Bowie's Ziggy Stardust Years",
    autor : "Reinhard, Kleist",
    image: "https://www.kulturkaufhaus.de/annotstream/9783551793621/COPL/Kleist-Reinhard/Starman---David-Bowies-Ziggy-Stardust-Years.jpg?sq=5",
    preis :"25,00",
    sprache : "Deutsch",
    seiten : "176",
    beschreibung : `1972 erlebte die Geburt des Rock'n'Roll-Messias Ziggy Stardust, dessen provokantes Spiel mit sexueller Identität und Geschlechterrollen den Grundstein für David Bowies Aufstieg zum "einflussreichsten Popmusiker aller Zeiten" (New Musical Express) legte.
    Starman erzählt von Aufstieg und Fall des wohl berühmtesten Alter Egos der Musikgeschichte.
    Fesselnd verwebt Reinhard Kleist die Genese der schrillen Kunstfigur sowohl mit David Bowies glücklosem Bemühen in der Londoner Musikszene vor Ziggy Stardust wie auch mit seinem Ringen mit der eigenen Schöpfung auf dem Höhepunkt des Ruhms: Immer rasanter verwandelt sich Bowie selbst zum egozentrischen Rockstar, der an seinem ausschweifenden Lebensstil zu scheitern droht...
    Reinhard Kleists elegante und treffsichere Zeichnungen werden in Starman durch die Farbgebung von Thomas Gilke kongenial ergänzt.`,
    kategorie:"Comics & Manga",
    "ISBN/GTIN": "978-3-551-79362-1",
    Produktart: "Buch" ,
    Einbandart:"Gebunden",
    Verlag:"Carlsen",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"30.11.2021",
    Gewicht:"827 g",
    ArtikelNr:"19760775",
    Genre:"Belletristik | Comic, Cartoon, Humor, Satire | Comic"
    },
    {titel: "Sonne und Beton - Die Graphic Novel",
    autor : "Oljanna, Haus",
    image: "https://www.kulturkaufhaus.de/annotstream/9783446269613/COPL/Haus-Oljanna/Sonne-und-Beton---Die-Graphic-Novel.jpg?sq=5",
    preis :"18,00",
    sprache : "Deutsch",
    seiten : "280",
    beschreibung : `Platz 2 der Graphic Novel-Bestsellerliste: Ein glühend heißer Sommer. Vier Jungs in Neukölln. Eine folgenschwere Entscheidung. Die Graphic Novel zum Bestseller "Sonne und Beton" von Comedy-Superstar Felix LobrechtDie junge talentierte Zeichnerin Oljanna Haus hat sich von Felix Lobrechts von der Kritik gefeiertem Debütroman zu einer rasanten Graphic Novel inspirieren lassen. In schnellen Schnitten inszeniert sie die authentischen Dialoge und lässt die unerbittliche Welt der Hochhausschluchten erstehen.`,
    kategorie:"Comics & Manga",
    "ISBN/GTIN": "978-3-446-26961-3",
    Produktart: "Buch" ,
    Einbandart:"Kartoniert, Paperback",
    Verlag:"hanserblau",
    Erscheinungsjahr:"2021",
    Erstverkaufstag:"25.10.2021",
    Gewicht:"748 g",
    ArtikelNr:"16397032",
    Genre:"Belletristik | Comic, Cartoon, Humor, Satire | Comic"
    },
]
export default books;
